version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: lp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lp-backend
    ports:
      - "5146:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017
      - DatabaseName=lpdb
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lp-frontend
    ports:
      - "4200:80" # A böngészőben a 4200-as porton éred majd el
    depends_on:
      - backend

volumes:
  mongo-data:
