apiVersion: apps/v1
kind: Deployment
metadata:
  name: minta-app
  namespace: default
spec:
  replicas: 1  # Kezdetben 1 példány fut
  selector:
    matchLabels:
      app: minta-app
  template:
    metadata:
      labels:
        app: minta-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Egyelőre sima Nginx, később ez lesz a ti kódotok
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: minta-app-svc
  namespace: default
spec:
  type: LoadBalancer 
  selector:
    app: minta-app
  ports:
  - port: 80
    targetPort: 80
