apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: elso-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.2.230-192.168.2.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: elso-reklam
  namespace: metallb-system
spec:
  ipAddressPools:
  - elso-pool
