apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-ha-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 15.6.21 # Stabil verzió
    helm:
      values: |
        # Registry javítás az Amazon szervereire
        global:
          imageRegistry: public.ecr.aws
        image:
          registry: public.ecr.aws
          repository: bitnami/mongodb

        # HA architektúra (Replica Set)
        architecture: replicaset
        replicaCount: 3

        # Hitelesítés
        auth:
          rootPassword: "SzuperErosMongo123"
          usernames:
          - "suli_admin" # Legalább egy felhasználót kér a chart
          passwords:
          - "SzuperErosUserPass123"
          databases:
          - "suli_adatok" # És mellé az adatbázist

        # Tárolás (Longhorn)
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 2Gi

        # Erőforrás korlátok (hogy ne egye meg a RAM-ot)
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
