apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-ha-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 15.6.21
    helm:
      values: |
        global:
          imageRegistry: public.ecr.aws
        image:
          registry: public.ecr.aws
          repository: bitnami/mongodb

        architecture: replicaset
        replicaCount: 3

        auth:
          rootPassword: "SzuperErosMongo123"
          usernames: ["suli_admin"]
          passwords: ["SzuperErosUserPass123"]
          databases: ["suli_adatok"]

        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 2Gi

        # --- ez azért kell mert alapból nem enged loadbalancer ip-t adni neki
        extraDeploy:
          - apiVersion: v1
            kind: Service
            metadata:
              name: mongodb-external-lb
            spec:
              type: LoadBalancer
              ports:
                - name: mongodb
                  port: 27017
                  targetPort: mongodb
              selector:
                app.kubernetes.io/name: mongodb
                app.kubernetes.io/instance: mongodb-ha-cluster

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
