apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-ha-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 15.6.21
    helm:
      values: |
        global:
          imageRegistry: public.ecr.aws
        image:
          registry: public.ecr.aws
          repository: bitnami/mongodb

        architecture: replicaset
        replicaCount: 3

        auth:
          rootPassword: "SzuperErosMongo123"
          usernames: ["suli_admin"]
          passwords: ["SzuperErosUserPass123"]
          databases: ["suli_adatok"]

        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 2Gi

        # A LoadBalancer mostantól aktív, de az IP-t a MetalLB választja ki
        service:
          type: LoadBalancer
          # Ha fix IP kellene, vedd le a kommentet az alábbi sorokról:
          # annotations:
          #   metallb.universe.tf/loadBalancerIPs: 192.168.2.234

        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
